// Package statemc provides a gRPC client for the Rust StateEngine service.
package statemc

import (
	"context"
	"fmt"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"

	// Proto-generated stubs (generated by scripts/generate_proto.sh).
	// Replace with actual import paths once stubs are committed.
	statepb "github.com/bc0de0/chitragupt/services/api-gateway/proto/state"
	commonpb "github.com/bc0de0/chitragupt/services/api-gateway/proto/common"
)

// Client wraps the StateEngine gRPC client.
type Client struct {
	conn   *grpc.ClientConn
	client statepb.StateEngineClient
}

// NewClient dials the Rust state machine and returns a ready-to-use Client.
func NewClient(addr string) (*Client, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	conn, err := grpc.DialContext(ctx, addr,
		grpc.WithTransportCredentials(insecure.NewCredentials()),
		grpc.WithBlock(),
	)
	if err != nil {
		return nil, fmt.Errorf("dial state machine %s: %w", addr, err)
	}
	return &Client{conn: conn, client: statepb.NewStateEngineClient(conn)}, nil
}

// Close releases the underlying connection.
func (c *Client) Close() error {
	return c.conn.Close()
}

// ── RPC wrappers ─────────────────────────────────────────────────────────────

func (c *Client) CreateSession(ctx context.Context, workspaceID, projectID string) (*statepb.CreateSessionResponse, error) {
	return c.client.CreateSession(ctx, &statepb.CreateSessionRequest{
		WorkspaceId: workspaceID,
		ProjectId:   projectID,
	})
}

func (c *Client) GetSessionState(ctx context.Context, sessionID, workspaceID string) (*commonpb.SessionStateProto, error) {
	return c.client.GetSessionState(ctx, &statepb.SessionQuery{
		SessionId:   sessionID,
		WorkspaceId: workspaceID,
	})
}

func (c *Client) ApplyTurnResult(
	ctx context.Context,
	sessionID string,
	entities []*commonpb.EntityProto,
	acUpdates []*commonpb.AcUpdateProto,
	costUSD float64,
) (*statepb.TurnResultResponse, error) {
	return c.client.ApplyTurnResult(ctx, &statepb.TurnResultRequest{
		SessionId:      sessionID,
		Entities:       entities,
		AcUpdates:      acUpdates,
		CostUsd:        costUSD,
		TurnCountDelta: 1,
	})
}

func (c *Client) RequestTransition(ctx context.Context, sessionID, targetPhase string) (*statepb.TransitionResponse, error) {
	return c.client.RequestTransition(ctx, &statepb.TransitionRequest{
		SessionId:   sessionID,
		TargetPhase: targetPhase,
	})
}

func (c *Client) RevisitPhase(ctx context.Context, sessionID, targetPhase string) (*statepb.RevisitResponse, error) {
	return c.client.RevisitPhase(ctx, &statepb.RevisitRequest{
		SessionId:   sessionID,
		TargetPhase: targetPhase,
	})
}
